SsdTestShell write 예외처리 및 테스트 구현 외 2
jayskang/CRA-Project-C_Team pull request #10
Opened 2024-05-03 07:48 UTC by ghdwlsrl3229

- 구현사항 변경에 따른 SsdTestShell write 예외처리 및 테스트 구현
- read, write 메서드 리팩터링
- SSD 인터페이스 method signiture 변경

2024-05-06 23:58 UTC, jayskang requested changes
전반적으로 굉장히 깔끔하게 작성되어서, 가볍게 읽어도 어떤 기능을 하는지 한눈에 잘 들어오네요~!
제가 추가 comment 작성한 부분들만 조금 더 리펙토링 하면 어떨까 싶은데요, 확인 부탁드리겠습니다^^

2024-05-06 23:58 UTC, jayskang commented on SsdTestShell/src/main/java/SsdTestShell.java
>              ssd.write(lba, data);
이 코드만 보고도 write 메서드에서 어떤 일을 하는지가 명확히 보이네요!
리펙토링이 잘 되어 보입니다^^

2024-05-06 23:58 UTC, jayskang commented on SsdTestShell/src/main/java/SsdTestShell.java
> +        boolean invalidDataFormat = !data.startsWith("0x") || data.length() != 10;
해당 부분을 메서드로 추출하고, if 문에서 inline으로 바로 호출하는것도 좋을 것 같습니다!

2024-05-06 23:58 UTC, jayskang commented on SsdTestShell/src/main/java/SsdTestShell.java
> +            System.out.println("read success: " + lba);
read 메서드의 다른 로직들과 맞춰서 해당 출력 부분을 메서드화 하는 건 어떨까요?

2024-05-06 23:58 UTC, jayskang commented on SsdTestShell/src/main/java/SsdTestShell.java
> +        boolean isLbaOutOfRange = param > MAX_LBA || param < MIN_LBA;
해당 부분을 메서드로 추출하고, if 문에서 inline으로 바로 호출하는것도 좋을 것 같습니다!

2024-05-07 00:05 UTC, ghdwlsrl3229 commented on SsdTestShell/src/main/java/SsdTestShell.java
> +        boolean invalidDataFormat = !data.startsWith("0x") || data.length() != 10;
확인했습니다! 메서드 추출과 설명 변수 중에 고민했던 부분인데, 메서드 추출로 바꿔도 좋을 것 같습니다.

2024-05-07 00:05 UTC, ghdwlsrl3229 commented on SsdTestShell/src/main/java/SsdTestShell.java
> +        boolean isLbaOutOfRange = param > MAX_LBA || param < MIN_LBA;
이 부분 마찬가지로 메서드 추출로 바꿔도 좋을 것 같습니다.

2024-05-07 00:10 UTC, ghdwlsrl3229 commented on SsdTestShell/src/main/java/SsdTestShell.java
>              ssd.write(lba, data);
감사합니다! 😊

2024-05-07 00:10 UTC, ParkJongNam approved these changes
리뷰 완료했습니다. 이해되지 않는 부분이나 클린코드 할 내용은 없는 것 같네요~
수고하셨습니다.

2024-05-07 00:25 UTC, ghdwlsrl3229 commented on SsdTestShell/src/main/java/SsdTestShell.java
> +            System.out.println("read success: " + lba);
exception 메시지 출력에 대해서만 메서드 추출이 이루어져 있어서, 다른 로직과 맞춰서 메서드화하는 건 다른 문제일 것 같습니다. 추후 출력 부분은 수정할 계획이므로, 일단 해당 PR에서는 수정하지 않는 것으로 하겠습니다.

2024-05-07 00:29 UTC, ghdwlsrl3229 commented
@jayskang 
리뷰 내용 반영하였습니다!
- lba, data 유효성 검사 로직 일부를 메서드 추출(isInvalidDataFormat, isLbaOutOfRange)

2024-05-07 00:30 UTC, jayskang approved these changes
넵! 수고하셨습니다!

2024-05-07 00:30 UTC, merged