[SSD READ] 빈파일 read 시 Unit Test 및 코드 구현
jayskang/CRA-Project-C_Team pull request #11
Opened 2024-05-03 08:14 UTC by gusejddl

빈파일 read UnitTest 작성
: UnitTest 시에 빈 파일을 생성하여 해당 파일을 read 했을 때 결과 값에 null 값이 들어가는 지 여부를 Check
fileread하여 String 배열로 return 하는 readFile() 함수 구현
해당 부분 Refactoring(추가로 Refactoring 할 부분 의견 많이 부탁 드립니다.)
범용적 사용을 위해 SSDConstraint 로 파일명 변경(AddressConstraint →SSDConstraint )

2024-05-06 23:40 UTC, jayskang requested changes
매직넘버를 상수화 시킨 부분과 의미에 맞도록 클래스 명 변경한 부분은 좋은 Refactoring인 것 같습니다.
제가 comment 단 부분 확인 하시고 수정 필요할지 확인 부탁드려요^^

2024-05-06 23:40 UTC, jayskang commented on SSD/src/test/java/ReadModuleTest.java
> +        fileWriter = new FileWriter(file);
read 후 읽은 데이터 값을 result.txt 파일에 매 번 새로 적어주도록 되어있는데요.
코드를 보면 nand.txt 파일 값을 오픈 해서 FileWriter를 생성하도록 되어있는 것 같습니다.
해당 부분 확인 부탁드려요^^

2024-05-06 23:40 UTC, jayskang commented on SSD/src/test/java/ReadModuleTest.java
> +        createWriteSampleFile("");
빈파일 호출 시 테스트의 경우 해당 메서드 호출은 크게 의미 없는 것 같아 보이는데요.
해당 라인은 테스트에서 삭제 해도 되지 않을까요??

2024-05-06 23:52 UTC, taylous reviewed
### IMHO... 🤔

제 나름대로 코멘트 남겨보았습니다!
읽어보시고 반영해보시면 좋을 것 같습니다!! 😃

2024-05-06 23:52 UTC, taylous commented on SSD/src/main/java/read/ReadModule.java
> +            return;
헛... 의도하지 않으신 `들여쓰기`가 있는 것 같습니다! 🤔

2024-05-06 23:52 UTC, taylous commented on SSD/src/main/java/read/ReadModule.java
>      }
오 해당 함수 `SSDConstraint` interface에 있어도 될 것 같네요!
사실 저도 비슷한 로직을 사용하고 있거든요

```java
private boolean checkAddressBoundary(int address) {
        try {
            if (SSDConstraint.MIN_BOUNDARY <= address && address < SSDConstraint.MAX_BOUNDARY) {
                this.errorLog = null;
                return true;
            }
// ...생략...
```

나중에 얘기나눠서 한 번 합쳐보는 것도 좋은 것 같습니다 ㅋㅋㅋ 😁

2024-05-06 23:52 UTC, taylous commented on SSD/src/test/java/ReadModuleTest.java
> +    private  SsdFileReader ssdFileReader;
들여쓰기가 안맞는 것 같습니다! 🤔

`file`, `ssdFileReader` 앞에 `공백` 없애주시면 더 깔끔하게 보일 것 같아요!

2024-05-07 00:05 UTC, gusejddl commented on SSD/src/test/java/ReadModuleTest.java
> +        fileWriter = new FileWriter(file);
아 네네! 이 부분은 Test용 nand.txt 파일을 만들어주는 부분인데 제가 명칭을 좀 애매하게 썼네요ㅎㅎㅎ 명칭을 수정해두겠습니다

2024-05-07 00:05 UTC, gusejddl commented on SSD/src/test/java/ReadModuleTest.java
> +        createWriteSampleFile("");
네네 해당 부분은 초기화 시 진행이 되겠네요. 삭제해두겠습니다

2024-05-07 00:10 UTC, gusejddl commented on SSD/src/main/java/read/ReadModule.java
> +            return;
엇 전혀 몰랐네요ㅋㅋㅋ감사합니다

2024-05-07 00:24 UTC, taylous approved these changes
## LGTM!!! 👏

고생하셨습니다!

2024-05-07 00:27 UTC, jayskang approved these changes

2024-05-07 00:30 UTC, merged