[Add] write 정상동작 테스트 추가
jayskang/CRA-Project-C_Team pull request #12
Opened 2024-05-03 08:16 UTC by taylous

## 📝 요약
`write`가 정상적으로 동작하는지 테스트하는 함수를 구현하였습니다.
`ReadModule`은 `Mock`으로 선언하고,
`SsdFileReader`은 `Spy`로 적용하여서 테스트 함수를 만들었습니다.

2024-05-06 23:38 UTC, gusejddl approved these changes

2024-05-06 23:38 UTC, gusejddl commented on SSD/src/main/java/write/WriteModule.java
> +            if (!value.startsWith("0x")) {
0x 도 MAX_BOUNDRY 처럼 별도로 분리하면 좋을 것 같습니다

2024-05-06 23:47 UTC, taylous commented on SSD/src/main/java/write/WriteModule.java
> +            if (!value.startsWith("0x")) {
아하! 맞습니다!! 안그래도 해당 부분을 `정규표현식`으로 처리하면 더 깔끔할 것 같아서 로직 수정하고 말씀하신 것 처럼 따로 분리하였습니다! 😃

2024-05-06 23:52 UTC, jayskang requested changes
개발하신 내용을 보면 저희가 기존에 SSD에서도 Exception을 발생시키는 것으로 하였다가, 요구사항을 다시 확인하고 Exception 발생 없이 변경하기로 하여 errorLog와 getErrorLog 메서드를 활용하여 Test개발하신것으로 보입니다.

해당 부분 관련해서 어떻게 적용할지를 함께 논의 후 결정하였으면 합니다.

1. 해당 기능은 현재 Test용도로만 사용되기 때문에 삭제하고, File Read, File Write를 별도 메서드로 분리 한 뒤 해당 메서드가 호출되었는지 여부로 Test 진행
2. 해당 기능을 SSD Test Shell 프로그램에서 활용할 수 있으면, 별도 Exction 발생 없이 오류 여부를 체크 가능할 것 같으니 그런 용도로 활용한다.

2024-05-06 23:58 UTC, taylous commented
@jayskang 

저는 외부로만 exception 안나가도록 하면 될거라고 생각해서 내부처리로만 사용했습니다. 🤔

내부적으로 throw를 한 이유는 `테스트` 떄문인데요.
`쓰기 동작`을 실행했을 때 정상적인 값인지 아닌지 체크할 방법이 생각나지 않아서 내부적으로 발생한 에러(exception)을 저장시켜 체크하도록 했습니다!

그런데 팀장님 의견 듣고나니 현정님께서 만드신 `읽기 동작`으로 체크할 수 있었을 것 같네요. 흠흠...

다른 팀원분들 의견없으시면 그냥 삭제하겠습니다!

2024-05-07 00:29 UTC, jayskang approved these changes
의견 반영해주셔서 감사합니다^^
수고하셨습니다!

2024-05-07 00:35 UTC, taylous commented
> 의견 반영해주셔서 감사합니다^^ 수고하셨습니다!

`conflict` 해결했습니다!

2024-05-07 00:46 UTC, merged