ssd 프로그램 호출 후 write 수행하는 기능 구현
jayskang/CRA-Project-C_Team pull request #25
Opened 2024-05-07 07:21 UTC by ghdwlsrl3229

먼저 구현된 read 함수 참고하여 유사하게 구현했습니다.

함수 호출 시 nand.txt 파일에 정상적으로 write가 됨을 테스트했습니다.
현재 nand.txt, result.txt의 경로가 임시적으로 설정되어 있기 때문에, 추후 경로의 올바른 설정이 필요해보입니다.

2024-05-07 07:46 UTC, jayskang requested changes
개발 수고하셨습니다!
제가 남긴 코멘트 참고하셔서 클래스 명 변경하는 부분 검토 부탁드리겠습니다^^

2024-05-07 07:46 UTC, jayskang commented on SsdTestShell/src/main/java/SSD.java
해당 클래스가 SSD 모듈을 시스템 콜 하기 위한 클래스가 맞을까요?
기존 SSD 모듈의 메인 클래스가 SSD로 되어있기 때문에 SsdExecutor와 같은 명칭으로 변경하는 건 어떨까요?

2024-05-08 00:25 UTC, ghdwlsrl3229 commented on SsdTestShell/src/main/java/SSD.java
저도 동의합니다. @ParkJongNam 클래스명 SsdExecutor로 수정할테니 참고 부탁드려요.

2024-05-08 00:31 UTC, ghdwlsrl3229 commented on SsdTestShell/src/main/java/SSD.java
@jayskang 클래스명 제안하신대로 변경했습니다. 확인 부탁드려요.

2024-05-08 00:32 UTC, merged